### ISSUE TITLE
Thanks for the guide. Question about only having a single "slide"

### ISSUE THREAD

**Issue by kaeedo** [sleepyfran/sharp-point#1]
Hello. I came across your blog post for the F# advent calendar. https://sleepyfran.github.io/blog/posts/fsharp/ce-in-fsharp/

This helped me immensely in my own library trying to create a DSL.

However, for my usecase I also would like the equivalent to what in this DSL is a single `slide`, but get an error stating that `Type constraint mismatch. The type 'DeckProperty' is not compatible with type 'DeckProperty list'`. This occurs also in this repository in `Program.fs` when you take out all `slide`s except one

Thanks

**Comment by sleepyfran** [comment]
Hey! Thanks a lot for bringing this up, here I thought I went through all the different cases and I forgot one of the most basic ones 😃 

Figured it out, though. The problem is in the `For` method, it's sad that the compiler cannot tell you directly, but just so that it's easier for you to spot these things: since the error was happening when combining two different things (the `title` custom property with the `slide` builder), the computation expression will call the `For` method to combine them together. If you recall in the blog post when we initially add support for the `slide` builder inside of the `deck` the first complaint we get is the missing `For` method.

So anyways, the solution is quite simple:
```fsharp
member inline x.For(prop: DeckProperty, f: unit -> DeckProperty) = [prop; f()]
```
This fixes it because the whole expression is made with the assumption that there's always going to be a list of stuff, but this is not the case when there's only two expressions, each from a different kind.

Hope I cleared it up a little! Let me know if there's anything else I can help with. Will push the changes to the repo 😃
